all:
	g++ -c ./SYSTEM/Display/displayVitor.cpp -o ./SYSTEM/Display/displayVitor.o
	g++ -c ./SYSTEM/Console/consoleVitor.cpp -o ./SYSTEM/Console/consoleVitor.o
	g++ main.cpp ./SYSTEM/Console/consoleVitor.o ./SYSTEM/Display/displayVitor.o -o main
	./main